version: '3.3'

services:
  graphql:
    build: .
    ports:
     - "8888"
    environment:
     - SERVICE_PORTS=8888
     - APP_ENV
    volumes:
     - .:/go/src/github.com/beinan/gql-server
  lb:
    image: 'dockercloud/haproxy:latest'
    links:
     - graphql
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
     - '8080:80'
  jaeger:
    image: 'jaegertracing/all-in-one:1.6'
    ports:
     - "5775/udp"
     - "6831/udp"
     - "6832/udp"
     - "5778"
     - "16686:16686"
     - "14268"
     - "9411"
    environment:
     - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    