package codegen

import (
	"bytes"
	"html/template"
	"io"
	"strings"

	"github.com/vektah/gqlparser/ast"
)

func GenerateModel(cfg GenConfig, w io.Writer) error {
	return generate(
		cfg, w, executeModelTmpl,
	)
}

const modelTmpl = `
//Generated by gql-server
//DO NOT EDIT
package gen

import (
	"github.com/beinan/gql-server/concurrent/future"
	"github.com/beinan/gql-server/graphql"
)

type ID = string
type StringOption = graphql.StringOption

type Future = future.Future

{{range .Definitions}}
type {{.Name}} struct {
  {{range .Fields}}
    {{if .Type | isImmediate}}
      {{.Name | titlePipe}} {{.| modelFieldTypePipe}}
    {{end}}
  {{end}}
}

{{end}}
`

func executeModelTmpl(doc *ast.SchemaDocument) []byte {
	funcMap := template.FuncMap{
		"modelFieldTypePipe": modelFieldTypePipe,
		"argumentPipe":       argumentPipe,
		"titlePipe":          strings.Title,
		"isImmediate":        isImmediate,
	}
	tmpl, err := template.New("model").Funcs(funcMap).Parse(modelTmpl)
	if err != nil {
		panic(err)
	}
	var buf bytes.Buffer
	tmpl.Execute(&buf, doc)
	return buf.Bytes()
}
